class BotCommands:
    StartCommand = "mirror_start"
    MirrorCommand = ["mirror_mirror", "mirror_m"]
    LeechCommand = ["mirror_leech", "mirror_l"]
    QbMirrorCommand = ["mirror_qbmirror", "mirror_qbm"]
    QbLeechCommand = ["mirror_qbleech", "mirror_qbl"]
    JdMirrorCommand = ["mirror_jdmirror", "mirror_jdm"]
    JdLeechCommand = ["mirror_jdleech", "mirror_jdl"]
    NzbMirrorCommand = ["mirror_nzbmirror", "mirror_nzbm"]
    NzbLeechCommand = ["mirror_nzbleech", "mirror_nzbl"]
    YtdlCommand = ["mirror_ytdl", "mirror_y"]
    YtdlLeechCommand = ["mirror_ytdlleech", "mirror_yl"]
    CloneCommand = "mirror_clone"
    CountCommand = "mirror_count"
    DeleteCommand = "mirror_del"
    CancelTaskCommand = ["mirror_cancel", "mirror_c"]
    CancelAllCommand = "mirror_cancelall"
    ForceStartCommand = ["mirror_forcestart", "mirror_fs"]
    ListCommand = "mirror_list"
    SearchCommand = "mirror_search"
    StatusCommand = "mirror_status"
    UsersCommand = "mirror_users"
    AuthorizeCommand = "mirror_auth"
    UnAuthorizeCommand = "mirror_unauth"
    AddSudoCommand = "mirror_addsudo"
    RmSudoCommand = "mirror_rmsudo"
    PingCommand = "mirror_ping"
    RestartCommand = "mirror_restart"
    StatsCommand = "mirror_stats"
    HelpCommand = "mirror_help"
    LogCommand = "mirror_log"
    ShellCommand = "mirror_shell"
    AExecCommand = "mirror_aexec"
    ExecCommand = "mirror_exec"
    ClearLocalsCommand = "mirror_clearlocals"
    BotSetCommand = ["mirror_bsetting", "mirror_bs"]
    UserSetCommand = ["mirror_usetting", "mirror_us"]
    SelectCommand = "mirror_sel"
    RssCommand = "mirror_rss"
